@eAppointmentService.API_HostAddress = http://localhost:5197

POST {{eAppointmentService.API_HostAddress}}/api/Auth/Login
Accept: application/json
Content-Type: application/json

{
  "userNameOrEmail": "string",
  "password": "string"

}

###
